Repository NALANCE/NALANCE-BE, pull requests merged in 2025-01, with the labels that each got.

#11 ✨ Ci : dev_deploy.yml파일에 application.yml 설정 추가
  .github/workflows/dev_deploy.yml
Labels: :sparkles: feature, :construction_worker: ci

#17 📝 Document - 이메일 인증 Swagger 작성
  build.gradle
  src/main/java/nalance/backend/domain/member/controller/EmailController.java
  src/main/java/nalance/backend/domain/member/dto/EmailDTO.java
  src/main/java/nalance/backend/domain/member/service/EmailCommandService.java
  src/main/java/nalance/backend/domain/member/service/impl/EmailCommandServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#18 📝 Document : 메일로 사진 보내기 Swagger 작성
  src/main/java/nalance/backend/domain/member/controller/EmailController.java
  src/main/java/nalance/backend/domain/member/dto/EmailDTO.java
  src/main/java/nalance/backend/domain/member/service/EmailCommandService.java
  src/main/java/nalance/backend/domain/member/service/impl/EmailCommandServiceImpl.java
Labels: :memo: docs

#26 ✨ Feature : 500에러시 디스코드 알림 기능 추가
  src/main/java/nalance/backend/global/error/exception/ExceptionAdvice.java
  src/main/java/nalance/backend/global/error/exception/alarmClient/dto/DiscordMessage.java
  src/main/java/nalance/backend/global/error/exception/alarmClient/service/DiscordClient.java
  src/main/resources/application-discord.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#28 📝 Document : 회원 관련 Swagger 작성
  src/main/java/nalance/backend/domain/member/controller/MemberController.java
  src/main/java/nalance/backend/domain/member/dto/MemberDTO.java
  src/main/java/nalance/backend/domain/member/service/MemberCommandService.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberCommandServiceImpl.java
  src/main/java/nalance/backend/domain/terms/dto/TermsDTO.java
  src/main/java/nalance/backend/domain/terms/entity/MemberAgree.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#30 🐛 Fix: CI/CD 연결 문제 해결
  .github/workflows/dev_deploy.yml
Labels: :bug: bug

#33 🐛 Fix : mysql driver 추가
  .github/workflows/dev_deploy.yml
  src/main/resources/application-database.yml
Labels: :bug: bug

#34 🐛 Fix : discord url 환경변수 설정
  .github/workflows/dev_deploy.yml
Labels: :bug: bug

#36 🐛 Fix : 서버 swagger cors 에러 해결
  src/main/java/nalance/backend/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: :bug: bug

#39 🐛 Fix : 인증 없이 접근 가능하도록 엔드포인트 허용
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :bug: bug

#42 📝 Document : 약관 관련 Swagger 작성
  src/main/java/nalance/backend/domain/member/controller/MemberController.java
  src/main/java/nalance/backend/domain/member/dto/MemberDTO.java
  src/main/java/nalance/backend/domain/member/entity/Member.java
  src/main/java/nalance/backend/domain/member/service/MemberQueryService.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberQueryServiceImpl.java
  src/main/java/nalance/backend/domain/terms/controller/TermsController.java
  src/main/java/nalance/backend/domain/terms/dto/MemberAgreeDTO.java
  src/main/java/nalance/backend/domain/terms/dto/TermsDTO.java
  src/main/java/nalance/backend/domain/terms/entity/MemberAgree.java
  src/main/java/nalance/backend/domain/terms/entity/Terms.java
  src/main/java/nalance/backend/domain/terms/service/TermsQueryService.java
  src/main/java/nalance/backend/domain/terms/service/impl/TermsQueryServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
Labels: :memo: docs, :sparkles: feature, :recycle: refactor

#40 📝 Document : Todo CRUD Swagger 작성 및 페이징 추가
  src/main/java/nalance/backend/domain/terms/dto/TermsDTO.java
  src/main/java/nalance/backend/domain/todo/controller/TodoController.java
  src/main/java/nalance/backend/domain/todo/dto/TodoDTO.java
  src/main/java/nalance/backend/domain/todo/repository/TodoRepository.java
  src/main/java/nalance/backend/domain/todo/service/TodoCommandService.java
  src/main/java/nalance/backend/domain/todo/service/TodoQueryService.java
  src/main/java/nalance/backend/domain/todo/service/impl/TodoCommandServiceImpl.java
  src/main/java/nalance/backend/domain/todo/service/impl/TodoQueryServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/validation/annotation/CheckPage.java
  src/main/java/nalance/backend/global/validation/annotation/ExistTodo.java
  src/main/java/nalance/backend/global/validation/validator/CheckPageValidator.java
  src/main/java/nalance/backend/global/validation/validator/TodoExistValidator.java
Labels: :memo: docs

#24 ✨ Feature : 카테고리 CRUD 구현
  .gitignore
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/dto/CategoryDTO.java
  src/main/java/nalance/backend/domain/category/entity/Category.java
  src/main/java/nalance/backend/domain/category/repository/CategoryRepository.java
  src/main/java/nalance/backend/domain/category/service/CategoryCommandService.java
  src/main/java/nalance/backend/domain/category/service/CategoryQueryService.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryQueryServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/error/handler/CategoryException.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
  src/main/resources/application-database.yml
Labels: :bug: bug, :memo: docs, :sparkles: feature

#48 ✨ Feature : 약관 조회 기능 구현
  src/main/java/nalance/backend/domain/terms/controller/TermsController.java
  src/main/java/nalance/backend/domain/terms/repository/TermsRepository.java
  src/main/java/nalance/backend/domain/terms/service/impl/TermsQueryServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/error/handler/TermsException.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
  src/main/java/nalance/backend/global/validation/annotation/ExistTerms.java
  src/main/java/nalance/backend/global/validation/validator/TermsExistValidator.java
Labels: :sparkles: feature

#50 ✨ Feature : 업로드된 파일(jpg, png) 이메일로 전송 기능 구현
  src/main/java/nalance/backend/domain/member/controller/EmailController.java
  src/main/java/nalance/backend/domain/member/dto/EmailDTO.java
  src/main/java/nalance/backend/domain/member/service/EmailCommandService.java
  src/main/java/nalance/backend/domain/member/service/impl/EmailCommandServiceImpl.java
  src/main/java/nalance/backend/global/email/EmailUtil.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
  src/main/java/nalance/backend/global/validation/annotation/CheckFile.java
  src/main/java/nalance/backend/global/validation/validator/CheckFileValidator.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#52 ✨ Feat : 카테고리 색상, 카테고리명 예외 처리 및 카테고리 생성 시, 멤버 설정 기능 추가
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/dto/CategoryDTO.java
  src/main/java/nalance/backend/domain/category/service/CategoryCommandService.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/repository/MemberRepository.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/validation/annotation/ExistCategoryColors.java
  src/main/java/nalance/backend/global/validation/validator/CategoryColorsExistValidator.java
Labels: :sparkles: feature

#41 ✨ Feature : 그래프 관련 API 구현
  src/main/java/nalance/backend/domain/category/repository/CategoryRepository.java
  src/main/java/nalance/backend/domain/todo/controller/GraphController.java
  src/main/java/nalance/backend/domain/todo/dto/GraphDTO.java
  src/main/java/nalance/backend/domain/todo/entity/Todo.java
  src/main/java/nalance/backend/domain/todo/repository/TodoRepository.java
  src/main/java/nalance/backend/domain/todo/service/GraphService.java
  src/main/java/nalance/backend/domain/todo/service/impl/GraphServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :memo: docs, :sparkles: feature

#57 ✨ Feature : 이메일 인증코드 템플릿 적용
  src/main/java/nalance/backend/global/email/EmailUtil.java
Labels: :sparkles: feature

#64 ♻️ Refactor : 캡쳐한 사진 보내는 기능 유저의 토큰 받도록 수정
  src/main/java/nalance/backend/domain/member/controller/EmailController.java
  src/main/java/nalance/backend/domain/member/service/EmailCommandService.java
  src/main/java/nalance/backend/domain/member/service/impl/EmailCommandServiceImpl.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :recycle: refactor

#66 ♻️ Refactor : 카테고리 CRUD memberId 토큰값으로 변경
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/service/CategoryCommandService.java
  src/main/java/nalance/backend/domain/category/service/CategoryQueryService.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryQueryServiceImpl.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :bug: bug, :recycle: refactor

#71 ✨ Feature : 로그인 관련 추가 기능 구현
  src/main/java/nalance/backend/domain/member/controller/MemberController.java
  src/main/java/nalance/backend/domain/member/dto/MemberDTO.java
  src/main/java/nalance/backend/domain/member/entity/RefreshToken.java
  src/main/java/nalance/backend/domain/member/repository/RefreshTokenRepository.java
  src/main/java/nalance/backend/domain/member/service/MemberCommandService.java
  src/main/java/nalance/backend/domain/member/service/MemberQueryService.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberQueryServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/jwt/TokenDTO.java
  src/main/java/nalance/backend/global/jwt/TokenProvider.java
  src/main/java/nalance/backend/global/jwt/dto/TokenDTO.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :sparkles: feature, :recycle: refactor

#72 🐛 Fix : Artifact 버전 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: bug

#74 🐛 Fix : 프론트 cors 에러 해결
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :bug: bug

#76 🐛 Fix : 카테고리 여러개 생성 시 색상 valid 응답 500대 오류 발생 및 중복값 요청 예외 처리
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/global/controller/BasicController.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
  src/main/java/nalance/backend/global/validation/validator/CollectionValidator.java
Labels: :bug: bug, :memo: docs

#78 📝 Document: CORS 설정 및 도메인 추가
  src/main/java/nalance/backend/domain/todo/controller/TodoController.java
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :memo: docs

#81 ♻️ Refactor : ResponseDTO에 categoryId 추가
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/dto/CategoryDTO.java
Labels: :sparkles: feature
