Repository NALANCE/NALANCE-BE, pull requests merged in 2025-02, with the labels that each got.

#83 ✨ Feature : 회원가입 과정에서 카테고리 생성 기능 추가
  src/main/java/nalance/backend/domain/category/service/CategoryCommandService.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/controller/MemberController.java
  src/main/java/nalance/backend/domain/member/dto/MemberDTO.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberCommandServiceImpl.java
Labels: :sparkles: feature

#86 🦺 Fix : 회원가입시 카테고리 생성 요청 값에 대한 예외 처리
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/dto/MemberDTO.java
Labels: :bug: bug

#88 ✨ Feat : 카테고리 순서 생성/수정 기능 추가
  src/main/java/nalance/backend/domain/category/controller/CategoryController.java
  src/main/java/nalance/backend/domain/category/dto/CategoryDTO.java
  src/main/java/nalance/backend/domain/category/entity/Category.java
  src/main/java/nalance/backend/domain/category/repository/CategoryRepository.java
  src/main/java/nalance/backend/domain/category/service/CategoryCommandService.java
  src/main/java/nalance/backend/domain/category/service/impl/CategoryCommandServiceImpl.java
  src/main/java/nalance/backend/global/error/code/status/ErrorStatus.java
Labels: :sparkles: feature

#91 🐛 Fix : 프론트 배포 주소 CORS 설정 추가
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :bug: bug

#92 🐛 Fix: 특정 유저의 카테고리만 반환하도록 수정
  src/main/java/nalance/backend/domain/category/repository/CategoryRepository.java
  src/main/java/nalance/backend/domain/todo/service/impl/GraphServiceImpl.java
Labels: :bug: bug

#97 ✨ Feature : todo 조회 응답에 todoId 포함
  src/main/java/nalance/backend/domain/todo/controller/TodoController.java
  src/main/java/nalance/backend/domain/todo/converter/TodoConverter.java
  src/main/java/nalance/backend/domain/todo/dto/TodoDTO.java
Labels: :bug: bug, :sparkles: feature

#98 ✨ Feature : Todo 생성 시 시작 시간/ 마무리 시간 추가 및 duration 계산
  src/main/java/nalance/backend/domain/todo/converter/TodoConverter.java
  src/main/java/nalance/backend/domain/todo/dto/TodoDTO.java
  src/main/java/nalance/backend/domain/todo/entity/Todo.java
  src/main/java/nalance/backend/domain/todo/service/impl/TodoCommandServiceImpl.java
Labels: :sparkles: feature

#100 🐛 [Fix] - Todo 조회 API에서 RequestBody 대신 RequestParam 적용
  src/main/java/nalance/backend/domain/todo/controller/TodoController.java
  src/main/java/nalance/backend/domain/todo/dto/TodoDTO.java
  src/main/java/nalance/backend/domain/todo/service/TodoQueryService.java
  src/main/java/nalance/backend/domain/todo/service/impl/TodoQueryServiceImpl.java
Labels: :bug: bug

#102 ♻️ Refactor : 프론트 배포 주소 수정
  src/main/java/nalance/backend/global/security/SecurityConfig.java
Labels: :recycle: refactor

#104 🐛 Fix : duration 저장 관련 엔티티 오류 수정
  src/main/java/nalance/backend/domain/todo/entity/Todo.java
  src/main/java/nalance/backend/domain/todo/service/impl/TodoCommandServiceImpl.java
Labels: :bug: bug

#106 ✨ Feature : todo 완료에서 미완료로 바꾸는 기능 추가
  src/main/java/nalance/backend/domain/todo/entity/Todo.java
Labels: :sparkles: feature

#108 ✨ Feature : 이메일 중복 검증 추가
  src/main/java/nalance/backend/domain/member/controller/EmailController.java
  src/main/java/nalance/backend/domain/member/entity/Member.java
  src/main/java/nalance/backend/domain/member/repository/MemberRepository.java
  src/main/java/nalance/backend/domain/member/repository/RefreshTokenRepository.java
  src/main/java/nalance/backend/domain/member/service/impl/EmailCommandServiceImpl.java
  src/main/java/nalance/backend/domain/member/service/impl/MemberCommandServiceImpl.java
Labels: :bug: bug, :sparkles: feature

#110 ♻️ Refactor : 이메일 검증 정규식으로 변경
  src/main/java/nalance/backend/domain/member/dto/EmailDTO.java
Labels: :sparkles: feature
